### ISSUE TITLE
Details on running the code with multiple cores

### ISSUE THREAD

**Issue by LinYuChi** [openai/mlsh#3]
Just want to check if we run the code in a correct way. If I want to run the code in 120 parallel instance as the paper suggests. Do I just use mpiexec command like the following command? or there is another way doing this?

`mpiexec -n 120 python3 main.py --task AntBandits-v1 --num_subs 2 --macro_duration 1000 --num_rollouts 2000 --warmup_time 20 --train_time 30 --replay False AntAgent`

**Comment by kvfrans** [comment]
We use mpirun:

`mpirun -np 120 python main.py --task AntBandits-v1 --num_subs 2 --macro_duration 1000 --warmup_time 20 --train_time 30 --num_rollouts 2000 --replay False AntAgent`
